### ISSUE TITLE
[Suggestion] Firefox Version

### ISSUE THREAD

**Issue by TooSpooky** [ilihh/sugoi-web#1]
Hello,

Any chance this could be ported to Firefox in the future?

Totally understand if not, haha.

Thanks for your time and take care.

**Comment by ilihh** [comment]
Firefox support added.

Installation for Firefox:
- Download the Source code (zip) archive from Releases
- Unpack the archive
- Delete manifest.json
- Rename manifest-firefox.json to manifest.json
- Open extensions page (about:debugging#/runtime/this-firefox)
- Press "Load Temporary Add-on" button and select manifest.json

**Comment by TooSpooky** [comment]
That was quick, thanks a ton.

In my limited knowledge from searching it seems

 if you go to about:config and set xpinstall.signatures.required to false 

then add 

"browser_specific_settings": {
  "gecko": {
    "id": "addon@example.com",
    "strict_min_version": "42.0"
  }
}

To the manifest it also lets you add it permanently via “add extension from file” from the extension menu. 

Thanks again and take care!
